#!/usr/bin/env python3
"""
Rebuild compact split_summary.json from existing pre-split app files.

Use case:
- You already have eve_http.jsonl / eve_tls.jsonl / etc.
- The old split_summary.json is too large or was generated by an older script.
- You do NOT want to split D:/eve.json again.
- You only want a lightweight summary that the pipeline/PDF can read.

Default VSCode/Code Runner usage:
    Open this file and Run Python File.

Default expected folder:
    <project_root>/data/eve_json/

Expected files:
    eve_http.jsonl
    eve_tls.jsonl
    eve_dns.jsonl
    eve_ssh.jsonl

Output:
    split_summary.json

Safety:
- This script never rewrites eve_http.jsonl / eve_tls.jsonl / etc.
- It rewrites only split_summary.json.
- Existing split_summary.json is backed up before replacement.
"""

from __future__ import annotations

import argparse
import gzip
import json
import re
import shutil
import sys
import time
from collections import Counter
from pathlib import Path
from typing import Any, Iterable, Literal, Optional, TextIO


AppName = Literal["http", "tls", "dns", "ssh"]
LabelMode = Literal[
    "valid_alert",
    "event_type_alert",
    "event_type_or_valid_alert",
    "alert_object",
]

# ============================================================
# DEFAULTS FOR SINGLE-CLICK / VSCODE RUN
# ============================================================

_THIS_FILE = Path(__file__).resolve()
try:
    PROJECT_ROOT = _THIS_FILE.parents[3]
except IndexError:
    PROJECT_ROOT = Path.cwd()

# Your current pipeline config uses project_root / data / eve_json.
SPLIT_APP_DIR = PROJECT_ROOT / "data" / "eve_json"
PORTS_FILE = PROJECT_ROOT / "config" / "ports.txt"

# Empty tuple = auto-detect from existing eve_<app>.jsonl files.
APP_TARGETS: tuple[AppName, ...] = ()

LABEL_MODE: LabelMode = "event_type_or_valid_alert"
PROGRESS_EVERY = 1_000_000
BACKUP_OLD_SUMMARY = True
PAUSE_ON_FINISH = True

VALID_APPS: tuple[AppName, ...] = ("http", "tls", "dns", "ssh")

IGNORED_ALERT_CATEGORIES = {
    "generic protocol decode",
    "generic protocol command decode",
}

PORT_TEMPLATE: dict[str, set[int]] = {
    "dns": {53},
    "http": {80, 8080, 8000, 8008, 8888},
    "tls": {443, 8443},
    "ssh": {22},
}


# ============================================================
# HELPERS
# ============================================================

def normalize_app(value: object) -> str:
    if value is None:
        return ""
    app = str(value).strip().lower()
    app = app.replace("-", "_").replace(".", "_").replace("/", "_")
    app = re.sub(r"[^a-z0-9_]+", "_", app)
    app = re.sub(r"_+", "_", app).strip("_")
    return app


def normalize_category(value: object) -> str:
    if value is None:
        return ""
    return str(value).strip().lower()


def now_iso() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%S%z", time.localtime())


def parse_app_targets(value: str | Iterable[str] | None) -> tuple[str, ...]:
    if value is None:
        return ()
    if isinstance(value, str):
        if not value.strip():
            return ()
        raw_items = value.split(",")
    else:
        raw_items = list(value)

    apps: list[str] = []
    for item in raw_items:
        app = normalize_app(item)
        if not app:
            continue
        if app not in VALID_APPS:
            raise ValueError(f"Invalid app target: {app!r}. Must be one of {sorted(VALID_APPS)}")
        if app not in apps:
            apps.append(app)
    return tuple(apps)


def auto_detect_apps(split_app_dir: Path) -> tuple[str, ...]:
    apps: list[str] = []
    for app in VALID_APPS:
        if (split_app_dir / f"eve_{app}.jsonl").exists() or (split_app_dir / f"eve_{app}.jsonl.gz").exists():
            apps.append(app)
    return tuple(apps)


def open_text_input(path: Path) -> TextIO:
    suffixes = "".join(path.suffixes).lower()
    if suffixes.endswith(".gz"):
        return gzip.open(path, "rt", encoding="utf-8", errors="ignore")
    return path.open("r", encoding="utf-8", errors="ignore")


def resolve_app_file(split_app_dir: Path, app: str) -> Path:
    plain = split_app_dir / f"eve_{app}.jsonl"
    gz = split_app_dir / f"eve_{app}.jsonl.gz"
    if plain.exists():
        return plain
    if gz.exists():
        return gz
    raise FileNotFoundError(f"Missing split file for app={app!r}: {plain} or {gz}")


def read_ports_file_if_exists(path: Path) -> dict[str, set[int]]:
    if not path.exists():
        return {app: set(ports) for app, ports in PORT_TEMPLATE.items()}

    out: dict[str, set[int]] = {}
    for raw_line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        app_raw, ports_raw = line.split("=", 1)
        app = normalize_app(app_raw)
        if app not in VALID_APPS:
            continue
        ports: set[int] = set()
        for item in ports_raw.split(","):
            item = item.strip()
            if not item:
                continue
            try:
                p = int(item)
                if 0 <= p <= 65535:
                    ports.add(p)
            except Exception:
                continue
        if ports:
            out[app] = ports

    for app, ports in PORT_TEMPLATE.items():
        out.setdefault(app, set(ports))
    return out


def alert_diagnostics(obj: dict[str, Any]) -> dict[str, Any]:
    event_type = normalize_app(obj.get("event_type"))
    alert = obj.get("alert")
    alert_is_dict = isinstance(alert, dict)

    category = ""
    severity = None
    signature = ""

    if alert_is_dict:
        category = normalize_category(alert.get("category"))
        severity = alert.get("severity")
        signature = str(alert.get("signature") or "").strip()

    severity_exists = severity is not None and str(severity).strip() != ""
    ignored_category = category in IGNORED_ALERT_CATEGORIES
    valid_alert = bool(alert_is_dict and severity_exists and not ignored_category)

    return {
        "event_type_alert": event_type == "alert",
        "alert_dict_exists": alert_is_dict,
        "alert_severity_exists": severity_exists,
        "ignored_alert_category": ignored_category,
        "valid_alert": valid_alert,
        "alert_category": category or "<missing>",
        "alert_signature": signature or "<missing>",
    }


def is_malicious_initial(obj: dict[str, Any], *, label_mode: LabelMode) -> bool:
    diag = alert_diagnostics(obj)
    mode = str(label_mode).strip().lower()

    if mode == "valid_alert":
        return bool(diag["valid_alert"])
    if mode == "event_type_alert":
        return bool(diag["event_type_alert"])
    if mode == "event_type_or_valid_alert":
        return bool(diag["event_type_alert"] or diag["valid_alert"])
    if mode == "alert_object":
        return bool(diag["alert_dict_exists"])

    raise ValueError(
        f"Invalid LABEL_MODE={label_mode!r}. "
        "Use valid_alert, event_type_alert, event_type_or_valid_alert, or alert_object."
    )


def counter_to_dict(counter: Counter) -> dict[str, int]:
    return {str(k): int(v) for k, v in counter.items()}


def count_file_lines(path: Path) -> int:
    if not path.exists():
        return 0
    count = 0
    with open_text_input(path) as f:
        for _ in f:
            count += 1
    return count


def atomic_write_json(path: Path, obj: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(obj, indent=2, ensure_ascii=False, default=str), encoding="utf-8")
    tmp.replace(path)


def backup_existing_summary(summary_path: Path) -> Optional[Path]:
    if not BACKUP_OLD_SUMMARY or not summary_path.exists():
        return None
    stamp = time.strftime("%Y%m%d_%H%M%S", time.localtime())
    backup_path = summary_path.with_name(f"split_summary.backup_{stamp}.json")
    shutil.copy2(summary_path, backup_path)
    return backup_path


# ============================================================
# SUMMARY REBUILD
# ============================================================

def scan_existing_app_file(
    *,
    app: str,
    path: Path,
    split_app_dir: Path,
    ports_file: Path,
    ports_used: set[int],
    label_mode: LabelMode,
    progress_every: int,
) -> dict[str, Any]:
    total_lines = 0
    empty_lines = 0
    malformed = 0
    valid_rows = 0

    label_counts = Counter()
    alert_diag_counts = Counter()

    t0 = time.perf_counter()

    print("\n--- REBUILD APP SUMMARY ---")
    print(f"App    : {app}")
    print(f"Input  : {path}")
    print("Mode   : scan existing split file only")

    with open_text_input(path) as f:
        for total_lines, line in enumerate(f, start=1):
            if progress_every > 0 and total_lines % progress_every == 0:
                elapsed = max(time.perf_counter() - t0, 1e-9)
                speed = total_lines / elapsed
                print(
                    f"[summary:{app}] scanned={total_lines:,} | valid={valid_rows:,} | "
                    f"B={label_counts.get('benign', 0):,} | M={label_counts.get('malicious', 0):,} | "
                    f"malformed={malformed:,} | speed={speed:,.0f} lines/s",
                    flush=True,
                )

            raw = line.rstrip("\n")
            if not raw.strip():
                empty_lines += 1
                continue

            try:
                obj = json.loads(raw)
                if not isinstance(obj, dict):
                    raise ValueError("JSON line is not an object")
            except Exception:
                malformed += 1
                continue

            valid_rows += 1

            diag = alert_diagnostics(obj)
            for k in (
                "event_type_alert",
                "alert_dict_exists",
                "alert_severity_exists",
                "ignored_alert_category",
                "valid_alert",
            ):
                if diag.get(k):
                    alert_diag_counts[k] += 1

            malicious = is_malicious_initial(obj, label_mode=label_mode)
            label_counts["malicious" if malicious else "benign"] += 1

    elapsed = time.perf_counter() - t0
    malformed_path = split_app_dir / f"malformed_{app}.jsonl"
    malformed_gz_path = split_app_dir / f"malformed_{app}.jsonl.gz"
    malformed_file: Optional[Path] = None
    if malformed_path.exists():
        malformed_file = malformed_path
    elif malformed_gz_path.exists():
        malformed_file = malformed_gz_path

    malformed_file_lines = count_file_lines(malformed_file) if malformed_file is not None else 0

    app_summary = {
        "app": str(app),
        "process_mode": "rebuild_summary_from_existing_split_files",
        "input_file": None,
        "output_dir": str(split_app_dir),
        "output_file": str(path),
        "ports_file": str(ports_file),
        "ports_used": sorted(int(p) for p in ports_used),
        "run_started_at": None,
        "run_finished_at": now_iso(),
        "elapsed_seconds": float(elapsed),

        # In rebuild mode, these counts refer to the already split app file,
        # not the original raw EVE file.
        "total_lines_scanned": int(total_lines),
        "empty_lines": int(empty_lines),
        "malformed": int(malformed),
        "unmatched_rows": 0,
        "matched_rows": int(valid_rows),
        "written_rows": int(valid_rows),
        "capped_skipped_rows": 0,
        "max_rows_per_app": 0,

        "label_policy": {
            "label_mode": str(label_mode),
            "malicious": (
                "event_type == alert OR valid Suricata alert evidence"
                if str(label_mode) == "event_type_or_valid_alert"
                else str(label_mode)
            ),
            "benign": "does not match the selected initial label mode",
            "ignored_alert_categories": sorted(IGNORED_ALERT_CATEGORIES),
            "note": (
                "This is a rebuilt initial pre-pipeline summary from existing split files. "
                "No raw split was performed and no app JSONL output was rewritten."
            ),
        },
        "label_counts": {
            "benign": int(label_counts.get("benign", 0)),
            "malicious": int(label_counts.get("malicious", 0)),
        },
        "alert_diagnostics": {
            "event_type_alert": int(alert_diag_counts.get("event_type_alert", 0)),
            "alert_dict_exists": int(alert_diag_counts.get("alert_dict_exists", 0)),
            "alert_severity_exists": int(alert_diag_counts.get("alert_severity_exists", 0)),
            "ignored_alert_category": int(alert_diag_counts.get("ignored_alert_category", 0)),
            "valid_alert": int(alert_diag_counts.get("valid_alert", 0)),
            "why_zero_malicious_hint": (
                "If event_type_alert > 0 but valid_alert == 0, strict valid_alert policy would reject alert rows. "
                "Current recommended mode is event_type_or_valid_alert."
            ),
        },
        "match_reason_counts": {
            "existing_split_file": int(valid_rows),
        },
        "malformed_file": str(malformed_file) if malformed_file is not None else None,
        "malformed_file_lines": int(malformed_file_lines),
        "output_size_bytes": int(path.stat().st_size) if path.exists() else 0,
        "detailed_summary_enabled": False,
        "summary_policy": (
            "Compact rebuilt summary: no per-port histograms, no event_type/app_proto full counters, "
            "and no alert signature/category top lists."
        ),
    }

    print(
        f"Done {app}: rows={valid_rows:,} | benign={label_counts.get('benign', 0):,} | "
        f"malicious={label_counts.get('malicious', 0):,} | malformed={malformed:,} | "
        f"elapsed={elapsed/60:.2f} min"
    )
    return app_summary


def recompute_aggregate(summary: dict[str, Any]) -> None:
    apps = summary.get("apps", {})
    written_counts: dict[str, int] = {}
    label_counts_by_app: dict[str, dict[str, int]] = {}
    output_files: dict[str, Optional[str]] = {}
    completed_apps: list[str] = []

    total_written = 0
    total_benign = 0
    total_malicious = 0

    for app, app_summary in sorted(apps.items()):
        completed_apps.append(str(app))
        written = int(app_summary.get("written_rows", 0))
        benign = int(app_summary.get("label_counts", {}).get("benign", 0))
        malicious = int(app_summary.get("label_counts", {}).get("malicious", 0))

        written_counts[str(app)] = written
        label_counts_by_app[str(app)] = {
            "benign": benign,
            "malicious": malicious,
        }
        output_files[str(app)] = app_summary.get("output_file")

        total_written += written
        total_benign += benign
        total_malicious += malicious

    summary["aggregate"] = {
        "apps_completed": completed_apps,
        "written_counts": written_counts,
        "label_counts_by_app": label_counts_by_app,
        "output_files": output_files,
        "total_written_all_completed_apps": int(total_written),
        "total_benign_all_completed_apps": int(total_benign),
        "total_malicious_all_completed_apps": int(total_malicious),
        "last_updated_at": now_iso(),
        "process_mode": "rebuild_summary_from_existing_split_files",
    }


def rebuild_split_summary(
    *,
    split_app_dir: Path,
    apps: Iterable[str],
    ports_file: Path,
    label_mode: LabelMode,
    progress_every: int,
) -> dict[str, Any]:
    split_app_dir = Path(split_app_dir)
    ports_file = Path(ports_file)

    if not split_app_dir.exists():
        raise FileNotFoundError(f"Split app directory not found: {split_app_dir}")

    app_targets = parse_app_targets(apps)
    if not app_targets:
        app_targets = auto_detect_apps(split_app_dir)
    if not app_targets:
        raise FileNotFoundError(
            f"No split app files found in {split_app_dir}. Expected eve_http.jsonl/eve_tls.jsonl/etc."
        )

    app_ports = read_ports_file_if_exists(ports_file)
    started = now_iso()
    t0 = time.perf_counter()

    summary_path = split_app_dir / "split_summary.json"
    backup_path = backup_existing_summary(summary_path)

    print("\n=== REBUILD SPLIT SUMMARY START ===")
    print(f"Input dir : {split_app_dir}")
    print(f"Apps      : {', '.join(app_targets)}")
    print(f"Summary   : {summary_path}")
    if backup_path:
        print(f"Backup    : {backup_path}")
    print("===================================")

    app_summaries: dict[str, Any] = {}
    for app in app_targets:
        app_file = resolve_app_file(split_app_dir, app)
        app_summaries[app] = scan_existing_app_file(
            app=app,
            path=app_file,
            split_app_dir=split_app_dir,
            ports_file=ports_file,
            ports_used=app_ports.get(app, set()),
            label_mode=label_mode,
            progress_every=progress_every,
        )

    elapsed = time.perf_counter() - t0
    finished = now_iso()

    summary: dict[str, Any] = {
        "schema_version": 4,
        "description": (
            "Compact split summary rebuilt from existing eve_<app>.jsonl files. "
            "No raw EVE split was performed."
        ),
        "process_mode": "rebuild_summary_from_existing_split_files",
        "input_file": None,
        "output_dir": str(split_app_dir),
        "ports_file": str(ports_file),
        "selected_apps_supported": list(VALID_APPS),
        "last_run_apps": list(app_targets),
        "last_run_started_at": started,
        "last_run_finished_at": finished,
        "last_run_elapsed_seconds": float(elapsed),
        "last_run_total_lines_scanned": int(sum(v.get("total_lines_scanned", 0) for v in app_summaries.values())),
        "last_run_no_selected_app_match": None,
        "label_mode": str(label_mode),
        "summary_policy": (
            "Lightweight app-level summary only. Heavy per-port, event_type, app_proto, alert category, "
            "and alert signature distributions are intentionally omitted."
        ),
        "apps": app_summaries,
        "aggregate": {},
        "backup_of_previous_summary": str(backup_path) if backup_path else None,
    }
    recompute_aggregate(summary)
    atomic_write_json(summary_path, summary)

    agg = summary["aggregate"]
    print("\n=== REBUILD SPLIT SUMMARY DONE ===")
    print(f"Summary       : {summary_path}")
    print(f"Apps          : {', '.join(agg['apps_completed'])}")
    print(f"Total rows    : {agg['total_written_all_completed_apps']:,}")
    print(f"Total benign  : {agg['total_benign_all_completed_apps']:,}")
    print(f"Total attack  : {agg['total_malicious_all_completed_apps']:,}")
    print(f"Elapsed       : {elapsed/60:.2f} min")
    return summary


# ============================================================
# CLI
# ============================================================

def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(
        description="Rebuild compact split_summary.json from existing eve_<app>.jsonl files.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    ap.add_argument("--split-app-dir", type=str, default=str(SPLIT_APP_DIR))
    ap.add_argument("--apps", type=str, default=",".join(APP_TARGETS))
    ap.add_argument("--ports-file", type=str, default=str(PORTS_FILE))
    ap.add_argument(
        "--label-mode",
        type=str,
        default=str(LABEL_MODE),
        choices=["valid_alert", "event_type_alert", "event_type_or_valid_alert", "alert_object"],
    )
    ap.add_argument("--progress-every", type=int, default=int(PROGRESS_EVERY))
    ap.add_argument("--no-pause", action="store_true")
    return ap.parse_args()


def main() -> None:
    args = parse_args()
    apps = parse_app_targets(str(args.apps))
    rebuild_split_summary(
        split_app_dir=Path(args.split_app_dir),
        apps=apps,
        ports_file=Path(args.ports_file),
        label_mode=str(args.label_mode),
        progress_every=int(args.progress_every),
    )


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print("\n=== ERROR ===")
        print(exc)
        raise
    finally:
        if PAUSE_ON_FINISH:
            try:
                if "--no-pause" not in sys.argv:
                    input("\nPress Enter to close...")
            except EOFError:
                pass
